## Makine Öğrenmesi

    İlk derste tensorflowdaki veri yapılarını ve nasıl kullanıldıklarını inceledik. Şimdi de bu veri yapılarını 
    kullanarak basit bir yapay sinir ağı oluşturalım.
    
    Aşağıdaki resimleri inceleyerek gerçek bir sinir hücresinin matematiksel olarak nasıl ifade edildiği hakkında 
    fikir sahibi olabilirsiniz.
![](ole.gif)
![](img18.gif) 

$$Sinyal = AktivasyonFonksiyonu({AgirlikMatrisi * Girdi + SapmaDegeri})$$

        Agirlik matrisleri (weights) yapay sinir aglarindaki hafizayi temsil ediyor.
        Yapay Sinir Aginda bu matrisleri, gelen veriler ve sonrasinda kullandigimiz optimizasyon algoritmasi
        ile sekillendiriyoruz. Yapay sinir agi boyle ogreniyor.

  
    
    

      Agirlik matrisini sadece girdilerle sekillendirerek aktivasyon fonksiyonunu esnek bir sekilde kullanmayiz. 
      Aktivasyon fonksiyonlarından biri olan sigmoid fonksiyonunun biassız ve bias eklenmiş grafiklerini
      inceleyelim.
$$ sigmoid: y = 1/(1+e^{-x}) $$

![](neuron_1.gif)![](sigmoid_1.png) ![](neuron_2.gif) ![](sigmoid_2.png)
    
    Aktivasyon fonksiyonu yapay sinir hucresinin urettigi sinyalin gucune gore hucrenin aktif olup olmayacagini
    veya ne olcude aktif olacagini belirler.
    sigmoid, tanh, step bu fonksiyonlara örnek verilebilir 

    Yapay zekanın ogrenmesini saglamak icin tahmin edilen veriler ile dogru verileri kıyaslayıp,
    aralarındaki kaybi(hatayi) hesaplayip azaltmamiz gerekiyor
    
    Bu hatayi hesaplamak icin;
        loss = tf.reduce_mean(tf.square(y_pred - y_real))    
    islemini kullanıyoruz. Burada oncelikle iki deger arasindaki farkı hesapladık. 
    Ardindan belirginlestirmek icin farkin karesini aldik. Son olarak da reduce_mean() 
    fonksiyonu ile kaybin ortalama degerini olctuk. Bu fonksiyon parametre olarak 
    input_tensor (giris matrisini) aliyor. Ek olarak hangi boyuta gore ortalama alinacagi
    belirlenebiliyor.

    Bu hatayi optimizasyon algoritmalari ile azaltabiliriz. Tensorflow bize hazir kullanabilecegimiz 
    bazi optimizasyon algoritmalari sunuyor. Biz bunlar arasindan GradientDescentOptimizer'i kullanacagiz.
    
    Aşağıdaki animasyonda bazı optimizasyon algoritmalarını minimum hatayı bulma hızları kıyaslanıyor.
![](Long-Valley-Training-Algorithms.gif)

    Bu algoritma N boyutlu hata matrisinde minumum noktayi bulmayi hedefliyor.
    Bu algoritmayi;
        optimizer = tf.train.GradientDescentOptimizer(0.5)
    seklinde kullanabiliriz. Girdigimiz 0.5 degeri ogrenme oranini temsil ediyor. 
    Bu degeri cok yuksek yaparsak minumum noktayi es gecebiliriz, cok kucuk yaparsak da
    minimum noktaya ulasmamiz cok uzun surebilir.

## Şimdi bu temel bilgilerle bir yapay sinir ağı tasarlayalım

    Oluşturulabilecek en basit yapay sinşr ağı 3 katmandan oluşuyor. 
    Bunlar giriş, gizli katman ve çıkış katmanı.
    Sadece veri giriş katmanı ve çıkış katmanlarıyla oluştursaydık oluşturacağımız modelin bir şeyleri öğrenme
    imkanı olmazdı. Verilen girdiye göre bir çıktı üreten sıradan bir program tasarlamış olurduk.
#### Veri Giriş Katmanı
    Bu katman adından da anlaşılacağı üzere modele verilerin girişini sağlıyor. Bu verilerin matris olarak ifade
    edilmesi gerekiyor. Ses, resim veya kelimeler bir şekilde matrislere çevrilip bu katman aracılığıyla modele
    iletilir.
#### Gizli Katman
    Bu katmana gelen veriler yukarda anlatılan işlemlerden geçer. Ağırlık matrisiyle çarpılır, bias eklenir 
    aktivasyon fonksiyonundan geçer ve elde edilen sonuç varsa diğer gizli katmanlara yoksa doğrudan çıkış katmanına
    iletilir.
#### Çıkış Katmanı
    Bu katmanda veriler modelden alınır. Buradan alınan çıktı amaca göre olasılık değerlerine dönüştürülebilir.
    
    Aşağıdaki animasyon sayesinde temel sinir ağının işleyişi hakkında fikir sahibi olabilirsiniz.
![](ann_3.gif)!

### Şimdi de bu modeli kodlayalım
    Giris verileri icin (X) -1 ile 1 arasinda rastgele sayilardan olusan 3x3 bir matris olusturduk.
    Gercek verileri temsil etmek icinde giris verilerinde biraz oynama yaptik. Bu ornekteki amacimiz 
    giris değerleri(X) ile yapay sinir agini egiterek ve test verileriyle kıyaslatarak her adimda gercek 
    degerlere (y_real) biraz daha yaklasmak.

In [16]:
import numpy as np
import tensorflow as tf

In [17]:
# Rastgele veriler oluşturduk
X = np.random.rand(3, 3).astype(np.float32)
y_real = X * 0.1 + 0.3
print(y_real)

[[ 0.39979604  0.36067289  0.34455836]
 [ 0.33221036  0.38466418  0.33547926]
 [ 0.33324617  0.32537547  0.3506926 ]]


In [18]:
weights = tf.Variable(tf.random_uniform([1], -1.0, 1.0)) # 1D array,  [-0.322323, 0.612312, ... , 0.712342]
biases = tf.Variable(tf.zeros([1])) # [0]

In [19]:
y_pred = weights * X + biases # giris verilerine gore bir tahmin olustur (sinir hucresi)

In [20]:
loss = tf.reduce_mean(tf.square(y_pred - y_real)) # kaybi hesapla

In [21]:
optimizer = tf.train.GradientDescentOptimizer(0.5) # ogrenme orani < 1
train = optimizer.minimize(loss) # modeli optimize et

    Eğer Variable() tanımlamışsak tensorflowun  bu değişkenleri tanıması için 
    tf.global_variables_initializer() fonksiyonunu çalıştırmamız gerekiyor.

In [22]:
init = tf.global_variables_initializer() # onemli, degiskenleri tanimla

    Eğitimin her aşamasında modelin tahmit ettiği değerlerin asıl değerlere yaklaşmasını umuyoruz

In [23]:
# Train
sess = tf.Session() # pointer
sess.run(init) # degiskenler tanimlandi
for step in range(1000):
    sess.run(train) # Modeli 1 kez egittik. train -> optimizer -> loss -> (y_pred, y_real) -> Wx_plus_B -> W, X, B

    if step % 200 is 0: # 200 adimda bir
        # agirlik matrisini ve sapma degerini yazdirdik. (Amacimiz  y_pred'in, y_real'e yaklasmasi)
        print(step, sess.run(weights), sess.run(biases)) 

0 [ 0.44382203] [ 0.15499692]
200 [ 0.10003161] [ 0.29998285]
400 [ 0.10000016] [ 0.29999992]
600 [ 0.10000016] [ 0.29999992]
800 [ 0.10000016] [ 0.29999992]


In [24]:
predicted = sess.run(y_pred) # Modelden verileri almak için run metodunu bir değişkene atıyoruz
print(predicted, end="\n\n")
print(y_real)

[[ 0.3997961   0.36067289  0.34455833]
 [ 0.33221033  0.38466424  0.33547923]
 [ 0.33324611  0.32537541  0.35069257]]

[[ 0.39979604  0.36067289  0.34455836]
 [ 0.33221036  0.38466418  0.33547926]
 [ 0.33324617  0.32537547  0.3506926 ]]


## Çıkarımlar

    Görüldüğü üzere bir yapay sinir ağı oluşturup eğitmek teorik olarak aşırı karmaşık gözükse de 
    matematiksel ifadesi oldukça anlaşılır ve kodlaması çok da zor değil.
    
    Prosedürü adım adım özetlemek gerekirse:
### 1- Veri Hazırlama
        Yukardaki örnekte kendimiz rastgele test ve eğitim veriler oluşturduk ama gerçekte bu veriler
        özenle hazırlanmış datasetlerden oluşuyor. Veri boyutunun çok büyük olduğu durumlarda big data çözümleriyle
        analiz edilip datasetlerin hazırlanması gerekiyor.
        
### 2- Yapay Sinir Ağı Modelini Oluşturma
        Amacımıza göre modelimizi ve ağ katmanlarını oluşturuyoruz. Her bir ağ katmanını tek tek
        oluşturmaktansatensorflowu sarmalayıcı bir kütüphane olan tflearni kullanabiliriz. Tabiki doğrudan tensorflow
        ile çalışmak bu işin temelini öğrenmemiz açısından daha sağlıklı olacaktır.
        
### 3- Modeli Eğitme
        Verilerin büyüklüğüne, sinir ağının kompleksliğine ve sistemin işlem kapasitesine göre modelin eğitim süresi
        saniyelerden aylara kadar değişebiliyor. Bu süreci hızlandırmak için ekran kartları veya paralel sistemler
        kullanılabilir.